var endpoint;

// Register a Service Worker.
navigator.serviceWorker.register('/scripts/service-worker.js')
.then(function(registration) {
  // Use the PushManager to get the user's subscription to the push service.
  return registration.pushManager.getSubscription()
  .then(function(subscription) {
    // If a subscription was found, return it.
    if (subscription) {
      return subscription;
    }

    // Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
    // send notifications that don't have a visible effect for the user).
    return registration.pushManager.subscribe({ userVisibleOnly: true });
  });
}).then(function(subscription) {
  endpoint = subscription.endpoint;

  // Send the subscription details to the server using the Fetch API.
  fetch('https://serviceworke.rs/push-rich/register', {
    method: 'post',
    headers: {
      'Content-type': 'application/json'
    },
    body: JSON.stringify({
      endpoint: subscription.endpoint,
    }),
  });
});

var varbody = "Fourth floor mens bathroom: the toilet in the stall is not flushing, please se...";
var varicon = "service-request_icon.png";

$("#send_push_sr,#send_push_cr").click(function(){
  if ($(this).attr("id") == "send_push_sr"){
    window.push_type = "sr";
    varbody = "Fourth floor mens bathroom: the toilet in the stall is not flushing, please se...";
    varicon = "service-request_icon.png";
  }
  else{
    window.push_type = "cr";
    varbody = "Your reservation for Large Conference Room has been approved! Click for more details.";
    varicon = "conference-room-reservations_icon";
  }
  console.log("test: "+push_type)
  $(".sending_notification_message").removeClass("sending_notification_message_off");
  $(".delay_display").html($("#notification_delay").val());
  setTimeout(function(){$(".sending_notification_message").addClass("sending_notification_message_off")},$("#notification_delay").val()*1000);

  var delay = $("#notification_delay").val();
  var ttl = 0;

  // Ask the server to send the client a notification (for testing purposes, in real
  // applications the notification will be generated by some event on the server).
  fetch('https://serviceworke.rs/push-rich/sendNotification?endpoint=' + endpoint + '&delay=' + delay +
        '&ttl=' + ttl,
    {
      method: 'post',
    }
  );
})

